name: Check Doctor Availability

on:
  schedule:
    - cron: '25 20 * * * '  # Esegue ogni giorno alle 8:00 UTC
  workflow_dispatch:

jobs:
  check_availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Usa la versione di Python necessaria

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 regex

      - name: Run availability check
        id: availability_check
        run: |
          python scrape_doctor.py > output.txt
          # Leggi l'output dallo script e memorizzalo come variabile d'ambiente
          echo "output_message<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send availability message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.output_message }}