name: Disponibilità medici di base

on:
  schedule:
    - cron: '55 06 * * * '  # Esegue ogni giorno alle 6:55 UTC --> 8:55
    - cron: '40 12 * * * '  # Esegue ogni giorno alle 14:40

  workflow_dispatch:

jobs:
  check_availability:
    runs-on: ubuntu-latest
    env:
      DOCTORS_LIST: ${{ secrets.MEDICOTEST }}  # DOCTORS_LIST environment secret "abc123,456def,..."

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 regex

      - name: Run availability check
        id: availability_check
        run: |
          python scrape_doctor.py > output.txt
          
          echo "output_message<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send availability message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.output_message }}