name: Disponibilità medici di base

on:
  schedule:
    - cron: '55 06 * * * '  # Esegue ogni giorno alle 6:55 UTC --> 8:55
    - cron: '45 13 * * * '  # Esegue ogni giorno alle 15:45
    - cron: '00 18 * * * '  # Esegue ogni giorno alle 20:00

  workflow_dispatch:

jobs:
  check_availability:
    runs-on: ubuntu-latest
    env:
      DOCTORS_LIST: ${{ secrets.MEDICOTEST }}  # DOCTORS_LIST environment secret "abc123,456def,..."

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 regex

      - name: Run availability check
        id: availability_check
        run: |
          # Esegui lo script Python e salva l'output in una variabile
          output_message=$(python scrape_doctor.py)
          
          # Nascondi l'output nei log per la privacy
          echo "::add-mask::$output_message"
          
          # Aggiungi l'output come variabile di ambiente per il passaggio successivo
          echo "output_message<<EOF" >> $GITHUB_ENV
          echo "$output_message" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: print output
        run: |
          echo "::add-mask::{env.output_message}"

      - name: Send availability message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.output_message }}